### PR TITLE
Introduce top-level `recv_future` module

### PR DESCRIPTION
**Pull request by thomaseizinger**
This creates consistency with the `send_future` module. To achieve this, we temporarily make the fields of `Receiver` public. This will go away once we merge #158 because it allows us to directly embed the `ChanPtr` and `BroadcastQueue` type in the `ReceiveFuture` instead of the actual `Receiver`.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
This PR actually made me wonder, why do we have the `RxWeak` type? We don't ever seem to use it :)

**Comment by thomaseizinger** [comment]
> This PR actually made me wonder, why do we have the `RxWeak` type? We don't ever seem to use it :)

I had a crack at removing this in https://github.com/Restioson/xtra/pull/160.

**Comment by thomaseizinger** [comment]
Setting this to draft until #160 is either merged or closed.

**Comment by thomaseizinger** [comment]
Going to continue here once #158 is merged.

**Comment by thomaseizinger** [comment]
I've merged https://github.com/Restioson/xtra/pull/158 into here under the assumption that it is not going to change much anymore until it is merged.

**Comment by thomaseizinger** [comment]
The commit log is a bit of a message because of the squash merging that I did but the final diff is correct :D

**Review by Restioson — APPROVED** [review]

**Comment by Restioson** [comment]
This is a pure refactor, right?

**Comment by thomaseizinger** [comment]
> This is a pure refactor, right?

Yes this is a pure refactor. The primary change is that we have only one `ReceiveFuture` now which is part of the public API. Once we land https://github.com/Restioson/xtra/pull/133, `Mailbox` will be a public type and thus I thought it is better if we treat `ReceiveFuture` the same way we treat `SendFuture`.

**Comment by Restioson** [comment]
Cool :) In that case, feel free to merge when ready

**Pull request merged**
