### PR TITLE
Remove outdated changelog entry

### PR DESCRIPTION
**Pull request by thomaseizinger**
These traits no longer exist within latest master.

### CODE REVIEW

**Comment by Restioson** [comment]
Doesn't RefCounter still exist?

**Comment by thomaseizinger** [comment]
> Doesn't RefCounter still exist? 

Technically no, there are two of them now 😁

I guess because the 2nd one didn't exist before, we don't need to mention it so in regards to breaking changes, it is only the one that got sealed.

**Comment by Restioson** [comment]
Well, RxRefCounter isn't public, but TxRefCounter still is (and, if I'm not wrong, is still sealed). TxRefCounter is also exposed under the name RefCounter I think

**Comment by Restioson** [comment]
Thanks!

**Pull request merged**
