### PR TITLE
Make `Address` implement `Sink` for `Handler`s that return `()`

### PR DESCRIPTION
**Pull request by thomaseizinger**
This is an alternative to https://github.com/Restioson/xtra/pull/70 and would therefore also help with https://github.com/Restioson/xtra/issues/64.

I read through https://github.com/Restioson/xtra/pull/48 which originally added a test that I had to remove because the API no longer exists now.

`StreamExt::forward` has (unfortunately) a different behaviour to what was "fixed" in https://github.com/Restioson/xtra/pull/48. In particular, it behaves the same as the original implementation and the current `Sink` implementation: It does **not** immediately return if the actor gets stopped but would only fail on the next item in the stream.

I think this is actually the correct behaviour. One could argue that the system is actually not broken if a stream that does not produce any items tries to forward to an actor that is stopped.

Let me know what you think.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
@Restioson Based on your [comment](https://github.com/Restioson/xtra/issues/71#issuecomment-1106492397), would you accept merging this if I drop the commits that remove `Address::attach_stream` and `Context::notify_interval`?

Without those commits, this PR is only a refactoring that removes the separate `AddressSink` but retains all functionality otherwise and should thus be non-controversial to land given that it deletes a fair bit of code?

**Comment by Restioson** [comment]
Sorry for letting this slip my mind too - I think overall the main issue is the tradeoff between code size/maintainability, and the size of the Address struct as a whole. Adding a sink as a field could increase it from the current 16 bytes (IIRC) to maybe 24 or 32 with padding, which could have implications if lists of actor addresses are kept. However, I'm not sure how much of an issue this will be considering that actors can share addresses and you don't need to implement message stealing yourself. What is your opinion on this?

**Comment by thomaseizinger** [comment]
> Adding a sink as a field could increase it from the current 16 bytes (IIRC) to maybe 24 or 32 with padding, which could have implications if lists of actor addresses are kept.

Yes, I thought about this but I figured that the added convenience and simplified codebase is worth it.

For this to seriously manifest, we would have to have _a lot_ of addresses in a list no?

I'd err on the side of perhaps optimising the other way in case the size of the struct ever becomes an issue: Adding a `SmallAddress` or something that does not implement `Sink`.

Additionally, I value the API over the implementation details. I am sure if we'd think hard about it, we could optimise the size of `Address` :)

**Comment by thomaseizinger** [comment]
Rebased to resolve conflicts, made no other changes.

**Comment by Restioson** [comment]
I've opened https://github.com/zesterer/flume/pull/102 in this interest - I will prototype something on the xtra side based on my fork shortly.

**Comment by thomaseizinger** [comment]
#81 is much better than this! Happy to close this in favor :)

**Comment by Restioson** [comment]
> Additionally, I value the API over the implementation details. I am sure if we'd think hard about it, we could optimise the size of Address :)

Speaking of this, if #85 works out, then it should be possible to have Address be exactly pointer sized, with atomic counters for strong and weak to replace the dedicated ref counter atomic (I will elaborate on this in #85 later). However, this is only if this change is reverted - Address would no longer be a Sink. However, I think it might be possible to expose a `fn address(&self) -> &Address` which would remove the `MessageSink` trait and with that a lot of maintenance burden. Of course, #85 itself is also far more complicated but I believe it makes sense for the library and I will elaborate on those reasons there, and we can discuss it if you are interested in doing so :)

**Comment by Restioson** [comment]
Would there be any issue with adding a method to convey the method to a sink?

**Comment by thomaseizinger** [comment]
> This can theoretically be done in an extension crate too, if xtra decides to take that route to improve maintainability. Nameability of types aside, it's semantically and functionally equivalent to https://docs.rs/futures/0.3.9/futures/sink/fn.unfold.html using Address::send

Fair point!

I think it would be good to try and distill the API down to the absolute minimum so happy to drop the `Sink` impl for now if that is what is necessary for that :)

**Pull request closed without merging**
