### PR TITLE
Fix `is_connected` for an `Actor` returning `StopSelf` in `stopping`

### PR DESCRIPTION
**Pull request by thomaseizinger**

### CODE REVIEW

**Comment by Restioson** [comment]
Ah, I see what you mean by this issue. If you can get it fixed I'll merge it, but unfortunately right now my bandwidth to write code myself is a little low due to university term and life 😅

**Comment by thomaseizinger** [comment]
> Ah, I see what you mean by this issue. If you can get it fixed I'll merge it, but unfortunately right now my bandwidth to write code myself is a little low due to university term and life 😅 

I am happy to write the code! Do you have an idea of how you want it fixed? It is not obvious when I looked at it :)

Is there a way of figuring out how many actors have been created on an address? Should we introduce a AtomicU32 that is shared across all contexts? I don't think we can use the address because that one could be cloned additionally!

**Comment by Restioson** [comment]
That could work, however, I wonder if something from the channels could be used? For instance, checking if dropping the address leads to the channel disconnecting. This could be either the broadcast or flume channel.

**Comment by thomaseizinger** [comment]
That sounds like a good idea. I'll explore that!

**Comment by thomaseizinger** [comment]
I've changed the implementation of `Address::is_connected` to use the `Sender` instead of the `RefCounter`. This fixes the test I added. What is your confidence on the remaining test suite that this works as expected in all circumstances?

**Comment by thomaseizinger** [comment]
Friendly ping @Restioson :)

**Comment by Restioson** [comment]
Oh sorry, I missed this. will take a look

**Comment by thomaseizinger** [comment]
> Oh sorry, I missed this. will take a look. Seems to still fail on smol though?

That is our famous flaky test, unrelated to this code change!

**Comment by Restioson** [comment]
> That is our famous flaky test, unrelated to this code change!

Seems like two failed?

**Comment by Restioson** [comment]
Rerunning it now

**Comment by thomaseizinger** [comment]
Now it seems to be hanging forever. Odd, they all passed on my machine ...

**Comment by thomaseizinger** [comment]
Force-pushed to re-trigger CI.

**Comment by Restioson** [comment]
Smol still seems to hang but everything else works

**Comment by thomaseizinger** [comment]
I can't reproduce this locally :(

Will have a deeper look at the code later but this test has failed on me in CI a couple of times!

**Comment by Restioson** [comment]
Interesting it only fails with smol 🤔

**Comment by thomaseizinger** [comment]
> Interesting it only fails with smol thinking

These tests are not run with any other runtime AFAIK.

**Comment by thomaseizinger** [comment]
> > Interesting it only fails with smol thinking
> 
> These tests are not run with any other runtime AFAIK. At least they use `smol_potat` which I assume only works with smol!

Yep, tokio runs `0` tests for example: https://github.com/Restioson/xtra/runs/5476184559?check_suite_focus=true#step:7:70

**Comment by Restioson** [comment]
I see, that makes sense then. I forgot that the other CI pipelines are just there to make sure it builds, since it's assumed that if it works on one executor, it should work on all of them

**Comment by Restioson** [comment]
I wonder if perhaps something about `#[smol_potat::test]` is making this fail. Might be worth trying to initialise the executor manually. Apologies by the way that I can't work much on this right now, it's just that university term is in full swing 😓

**Comment by thomaseizinger** [comment]
I'll see to add some tests using tokio and see if that passes.

**Comment by thomaseizinger** [comment]
@Restioson It seems everything passes with the tokio executor! What do you want to do about this situation? :D

**Comment by Restioson** [comment]
This seems to be some kind of smol scheduling issue, in that case. Happy to merge!

**Pull request merged**
